version: '3.8'

services:

  files_service:
    restart: always
    build: .
    working_dir: /files-service
    command: ["/bin/bash", "/files-service/scripts/entrypoint.sh"]
    volumes:
      - files_service_data:/files
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - files_postgres
    networks:
      - db_network
      - backend_network
    container_name: files_service

  files_postgres:
    image: postgres:14.5-alpine
    restart: always
    user: "70:70"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - db_network
    container_name: files_postgres

  files_nginx:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./services/nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - files_service_data:/var/html/files/
    ports:
      - "80:80"
    networks:
      - backend_network
    depends_on:
      - files_postgres
    container_name: files_nginx

networks:
  backend_network:
  db_network:

volumes:
  files_service_data:
  postgres_data:
